apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ke2l3eusp-python
  janus-idp.io/tekton: ke2l3eusp-python
  backstage.io/kubernetes-id: ke2l3eusp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ke2l3eusp-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
