apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ke2l3eusp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ke2l3eusp-python 
  name: ke2l3eusp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ke2l3eusp-python 
